### ISSUE TITLE
Unified data source

### ISSUE THREAD

**Issue by pzb** [GSA/data#51]
Currently data for `.gov` domains is very spread out which makes access hard for users.  There are at least four different possible public data sources, each of which contains slightly different information:

* Querying `whois.nic.gov` on port 43 provides:
  * Status (ACTIVE) or "No match"
* The Web-based whois at https://www.dotgov.gov/portal/web/dotgov/whois provides:
  * Agency
  * Organization
  * Status (same as port 43 whois)
* The CSV files provide:
  * Domain Type
  * Agency
  * City
  * State
* The `gov-servers.net.` name servers provide
  * Name servers for the domain
  * DNSSEC information for domain

None of these data sources provide registration dates, such as Creation Date, Updated Date, or Expiration Date.

It would be very useful if all the information on a domain were available in a single location and machine readable instead of being spread across many locations.  The dates are very helpful when interacting with the domains as it allows users with access to additional domain details (such as contact information for the registrant) to determine if the domain details have had updates since last retrieved.  Expiration information is helpful to determine how long is appropriate to accept authorization from the current operator for actions and when authorization should be renewed.

**Comment by konklone** [comment]
@pzb Thanks for laying this out in detail.

I'm not sure that publishing the Updated Date and Expiration Date in the CSV would be useful for determining "how long is appropriate to accept authorization from the current operator for actions and when authorization should be renewed.", because these would not be real-time data sources and could be 1 or more months' delayed.

I am also not sure whether "Status" is useful. Are there domains for which the Status is not `ACTIVE`?

You previously requested the Organization field in #33, which I agree would be helpful to many consumers, myself  and @h-m-f-t included.

Also cc-ing @smarina04 so she sees the request.

**Comment by pzb** [comment]
I agree that having the data updated once a month or less is less than ideal.  I was kind of hoping dotgov.gov might add it to the data they offer via web whois.  Bonus points if the data was available via JSON or some other structured format.

**Comment by smarina04** [comment]
.gov domains list is now updated weekly, and the organization field has been made more prominent during the registration and renewal process.
