### ISSUE TITLE
404s

### ISSUE THREAD

**Issue by MIams-REISys** [GSA/data#7]
https://gsa.github.io/data/dotgov-domains/2014-12-01-full.csv on https://18f.gsa.gov/2014/12/18/a-complete-list-of-gov-domains/ and https://github.com/GSA/data

CSV link on https://github.com/GSA/data

http://gsa.github.io/data/source-code-policy/ and https://gsa.github.io/data/articles/introducing-cfpb-open-tech/ on https://gsa.github.io/data/

Love the site and the transparency!!

**Comment by konklone** [comment]
Ahhh, I understand what happened. 

@gbinal: There's a conflict between this repository's name, and the existing `/data/` directory on https://gsa.github.io/data/, which is managed by the `gsa.github.io` repository. 

When we updated the `gsa.github.io` website (my HTTPS fix), it then gave priority to that repo's claim to `/data/`, and the `.csv` is a 404 because it's looking in that other repo.

We should resolve the conflict. Either `gsa.github.io` should stop using a `/data/` folder, or we should rename this repo to something else (`datasets`?). 

I suggest the latter. In that case, GitHub would handle redirects for this repo, and we can update our blog post, but we'd probably want to go drop a few `<meta redirect>` files in the `gsa.github.io` repo to make sure those specific URLs always redirect to the new location.

**Comment by konklone** [comment]
As for the source-code-policy and CFPB article links, I think those are just artifacts of the fork of CFPB? So the links to them should be removed.

And actually - is `gsa.github.io` being used for anything? Is that the repo we should remove or rename instead?

**Comment by gbinal** [comment]
Hi folks,  

Sorry for the slow followup to this, but yes, @konklone was exactly right.  The problem was addressed shortly after you filed this issue but you were right that it was also worth removing the unrelated CFPB artifacts.  This has now been done.  

Thanks for your help, @MIams-REISys.
